### PR TITLE
DEV-4548: Multiple fixes for the EH8010 YAML file

### PR DESCRIPTION
**Pull request by shmuelhazan**
This PR contains multiple fixes and reworks the EH8010 YAML file.

### CODE REVIEW

**Comment by dima1308** [comment]
@shmuelhazan is it possible that the device got stuck when running the script?
When the device got stuck, nothing was written on the log...
Please see below:
```
dimag@dali:~/git/ci-automation$ setup_script/main.py setup_script/devices/portfolio-eh8010.yaml --io-log log --command "/usr/bin/telnet 10.40.0.53 3004" --device_user root --device_password BabaGamp#45 --device_ip 10.61.119.5  --device_default_gateway 10.61.119.1
INFO:__main__:Starting state InitState...
INFO:__main__:Running state actions...
INFO:device_model:Writing output: "<enter>"
INFO:__main__:Waiting 300 seconds for any of the following patterns: ['.{2,}>', 'sw login: ', 'Password: ', '=> ', 'NAND erase.part:(\\n|\\r\\n|.)+OK', '# ', 'Hit any key to stop autoboot:']...
INFO:__main__:Timed out.
Traceback (most recent call last):
  File "/local/home/dimag/git/ci-automation/setup_script/PexpectDeviceIO.py", line 23, in read_expect_regex
    match = self._session.expect(compiled_list_of_regex, timeout=timeout)
  File "/user/dimag/.local/lib/python3.6/site-packages/pexpect/spawnbase.py", line 344, in expect
    timeout, searchwindowsize, async_)
  File "/user/dimag/.local/lib/python3.6/site-packages/pexpect/spawnbase.py", line 372, in expect_list
    return exp.expect_loop(timeout)
  File "/user/dimag/.local/lib/python3.6/site-packages/pexpect/expect.py", line 181, in expect_loop
    return self.timeout(e)
  File "/user/dimag/.local/lib/python3.6/site-packages/pexpect/expect.py", line 144, in timeout
    raise exc
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7fcb5a600940>
command: /usr/bin/telnet
args: ['/usr/bin/telnet', '10.40.0.53', '3004']
buffer (last 100 chars): b" '^]'.\r\n\r\nser2net port 3004 device /dev/com4 [115200 N81] (Debian GNU/Linux)\r\n\r\n\r\n\x1b7\x1b[500C\x1b[500B\x1b[6n"
before (last 100 chars): b" '^]'.\r\n\r\nser2net port 3004 device /dev/com4 [115200 N81] (Debian GNU/Linux)\r\n\r\n\r\n\x1b7\x1b[500C\x1b[500B\x1b[6n"
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 740
child_fd: 8
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: <SecretFileWriter name='log'>
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile(b'.{2,}>')
    1: re.compile(b'sw login: ')
    2: re.compile(b'Password: ')
    3: re.compile(b'=> ')
    4: re.compile(b'NAND erase.part:(\\n|\\r\\n|.)+OK')
    5: re.compile(b'# ')
    6: re.compile(b'Hit any key to stop autoboot:')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup_script/main.py", line 154, in <module>
    main(*get_args())
  File "setup_script/main.py", line 138, in main
    result = device_setup.run_state(model.first_state)
  File "/local/home/dimag/git/ci-automation/setup_script/DeviceSetup.py", line 24, in run_state
    match = self._process_input(state.inputs)
  File "/local/home/dimag/git/ci-automation/setup_script/DeviceSetup.py", line 33, in _process_input
    found_pattern, captured_variables = self._device_io.read_expect_regex(regex_list, input_model.timeout)
  File "/local/home/dimag/git/ci-automation/setup_script/PexpectDeviceIO.py", line 34, in read_expect_regex
    raise TimeoutError(e)
TimeoutError: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7fcb5a600940>
command: /usr/bin/telnet
args: ['/usr/bin/telnet', '10.40.0.53', '3004']
buffer (last 100 chars): b" '^]'.\r\n\r\nser2net port 3004 device /dev/com4 [115200 N81] (Debian GNU/Linux)\r\n\r\n\r\n\x1b7\x1b[500C\x1b[500B\x1b[6n"
before (last 100 chars): b" '^]'.\r\n\r\nser2net port 3004 device /dev/com4 [115200 N81] (Debian GNU/Linux)\r\n\r\n\r\n\x1b7\x1b[500C\x1b[500B\x1b[6n"
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 740
```

**Comment by dima1308** [comment]
@shmuelhazan is it possible that the device got stuck when running the script?
When the device got stuck, nothing was written on the log...
Please see below:
```
dimag@dali:~/git/ci-automation$ setup_script/main.py setup_script/devices/portfolio-eh8010.yaml --io-log log --command "/usr/bin/telnet 10.40.0.53 3004" --device_user root --device_password ****** --device_ip 10.61.119.5  --device_default_gateway 10.61.119.1
INFO:__main__:Starting state InitState...
INFO:__main__:Running state actions...
INFO:device_model:Writing output: "<enter>"
INFO:__main__:Waiting 300 seconds for any of the following patterns: ['.{2,}>', 'sw login: ', 'Password: ', '=> ', 'NAND erase.part:(\\n|\\r\\n|.)+OK', '# ', 'Hit any key to stop autoboot:']...
INFO:__main__:Timed out.
Traceback (most recent call last):
  File "/local/home/dimag/git/ci-automation/setup_script/PexpectDeviceIO.py", line 23, in read_expect_regex
    match = self._session.expect(compiled_list_of_regex, timeout=timeout)
  File "/user/dimag/.local/lib/python3.6/site-packages/pexpect/spawnbase.py", line 344, in expect
    timeout, searchwindowsize, async_)
  File "/user/dimag/.local/lib/python3.6/site-packages/pexpect/spawnbase.py", line 372, in expect_list
    return exp.expect_loop(timeout)
  File "/user/dimag/.local/lib/python3.6/site-packages/pexpect/expect.py", line 181, in expect_loop
    return self.timeout(e)
  File "/user/dimag/.local/lib/python3.6/site-packages/pexpect/expect.py", line 144, in timeout
    raise exc
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7fcb5a600940>
command: /usr/bin/telnet
args: ['/usr/bin/telnet', '10.40.0.53', '3004']
buffer (last 100 chars): b" '^]'.\r\n\r\nser2net port 3004 device /dev/com4 [115200 N81] (Debian GNU/Linux)\r\n\r\n\r\n\x1b7\x1b[500C\x1b[500B\x1b[6n"
before (last 100 chars): b" '^]'.\r\n\r\nser2net port 3004 device /dev/com4 [115200 N81] (Debian GNU/Linux)\r\n\r\n\r\n\x1b7\x1b[500C\x1b[500B\x1b[6n"
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 740
child_fd: 8
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: <SecretFileWriter name='log'>
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile(b'.{2,}>')
    1: re.compile(b'sw login: ')
    2: re.compile(b'Password: ')
    3: re.compile(b'=> ')
    4: re.compile(b'NAND erase.part:(\\n|\\r\\n|.)+OK')
    5: re.compile(b'# ')
    6: re.compile(b'Hit any key to stop autoboot:')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup_script/main.py", line 154, in <module>
    main(*get_args())
  File "setup_script/main.py", line 138, in main
    result = device_setup.run_state(model.first_state)
  File "/local/home/dimag/git/ci-automation/setup_script/DeviceSetup.py", line 24, in run_state
    match = self._process_input(state.inputs)
  File "/local/home/dimag/git/ci-automation/setup_script/DeviceSetup.py", line 33, in _process_input
    found_pattern, captured_variables = self._device_io.read_expect_regex(regex_list, input_model.timeout)
  File "/local/home/dimag/git/ci-automation/setup_script/PexpectDeviceIO.py", line 34, in read_expect_regex
    raise TimeoutError(e)
TimeoutError: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7fcb5a600940>
command: /usr/bin/telnet
args: ['/usr/bin/telnet', '10.40.0.53', '3004']
buffer (last 100 chars): b" '^]'.\r\n\r\nser2net port 3004 device /dev/com4 [115200 N81] (Debian GNU/Linux)\r\n\r\n\r\n\x1b7\x1b[500C\x1b[500B\x1b[6n"
before (last 100 chars): b" '^]'.\r\n\r\nser2net port 3004 device /dev/com4 [115200 N81] (Debian GNU/Linux)\r\n\r\n\r\n\x1b7\x1b[500C\x1b[500B\x1b[6n"
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 740
```

**Comment by shmuelhazan** [comment]
@dima1308 I tried multiple times but I have not managed to reproduce the issue on the CI setup. Maybe it is related to a specific SW version/device?

**Comment by dima1308** [comment]
> @dima1308 I tried multiple times but I have not managed to reproduce the issue on the CI setup. Maybe it is related to a specific SW version/device?

I tried to load the latest master from NFS. Maybe the difference is the fact that I use NFS and you load SW from the flash? 
See: https://jira-siklu.atlassian.net/wiki/spaces/SIKLURND/pages/2083848222/8010+NFS+and+TFTP+boot+using+TpLink+UE300+USB+to+Ethernet+adapter

**Review by dima1308 — APPROVED** [review]

**Pull request merged**
